<div class="page-title category-title"><h1><?php // $this->getCategoryTitle(); ?></h1></div>
<div class="category-products">
    <ul class="products-grid">
        <li class="item">
            <div class="wrapper-hover">
                <a href="http://fem.dev/2-tone-stockings" title="2 Tone Stockings" class="product-image">
                    <img src="http://fem.dev/media/catalog/product/cache/1/small_image/270x414/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" alt="2 Tone Stockings">
                </a>
                <p class="product-name"><a href="http://fem.dev/2-tone-stockings" title="2 Tone Stockings">2 Tone Stockings</a></p>
                <img src="imege.jpeg">
                <div class="price-box">
                    <div class="price">
                        <span itemprop="priceCurrency" content="GBP"></span>
                        <span class="price">£11.42</span>
                    </div>
                </div>
            </div>
        </li>
        <li class="item">
            <div class="wrapper-hover">
                <a href="http://fem.dev/2-tone-stockings" title="2 Tone Stockings" class="product-image">
                    <img src="http://fem.dev/media/catalog/product/cache/1/small_image/270x414/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" alt="2 Tone Stockings">
                </a>
                <p class="product-name"><a href="http://fem.dev/2-tone-stockings" title="2 Tone Stockings">2 Tone Stockings</a></p>
                <img src="imege.jpeg">
                <div class="price-box">
                    <div class="price">
                        <span itemprop="priceCurrency" content="GBP"></span>
                        <span class="price">£11.42</span>
                    </div>
                </div>
            </div>
        </li>        <li class="item">
            <div class="wrapper-hover">
                <a href="http://fem.dev/2-tone-stockings" title="2 Tone Stockings" class="product-image">
                    <img src="http://fem.dev/media/catalog/product/cache/1/small_image/270x414/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" alt="2 Tone Stockings">
                </a>
                <p class="product-name"><a href="http://fem.dev/2-tone-stockings" title="2 Tone Stockings">2 Tone Stockings</a></p>
                <img src="imege.jpeg">
                <div class="price-box">
                    <div class="price">
                        <span itemprop="priceCurrency" content="GBP"></span>
                        <span class="price">£11.42</span>
                    </div>
                </div>
            </div>
        </li>
    </ul>
</div>