<?php foreach ($GLOBALS['errors'] as $error) : ?>
    <div class="isa_error"><i class="fa fa-times-circle"></i><?php echo $error; ?></div>
<?php endforeach; ?>
<div><span><a href="<?php echo $this->getUrl('sitemap'); ?>">Try again ?</a></span></div>

<!--
<div class="isa_success">
    <i class="fa fa-check"></i>
    Replace this text with your own text.
</div>

<div class="isa_warning">
    <i class="fa fa-warning"></i>
    Replace this text with your own text.
</div>

<div class="isa_error">
    <i class="fa fa-times-circle"></i>
    Replace this text with your own text.
</div>

<div class="isa_info">
    <i class="fa fa-info-circle"></i>
    Replace this text with your own text.
</div>
-->