<!DOCTYPE HTML>
<html>
<head>
    <title>Seo Framework <?php echo $this->getVersion(); ?></title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <script src="https://use.fontawesome.com/e8c154b487.js"></script>
    <link rel="stylesheet" href="<?php echo $this->getThemeCssPath(); ?>style.css"/>
</head>
<body>
<div id="wrapper">
