<br><br>
<div class="content">

    <span> Welcome to Online Web Tools PRO </span>
    <p> What does our project do?
        We help you solve most of the mistakes that are associated with the promotion of your Internet resource. </p>
    <p>
        For this, we have a sufficiently powerful set of tools that will help you identify problems and get
        recommendations for their solution
    </p>
    <p>
        With the help of our resource you will be able to cover over 90% of the problems associated with common common
        mistakes that prevent the promotion of your Internet resource up to the search engines
    </p>
</div>
<br><br>
<p><b>Start typing a name in the input field below:</b></p>
<form>
    First name: <input type="text" onkeyup="showHint(this.value)">
</form>
<p>Suggestions: <span id="txtHint"></span></p>


<script>
    function showHint(str) {
        if (str.length == 0) {
            document.getElementById("txtHint").innerHTML = "";
            return;
        } else {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("txtHint").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "http://seo.dev/ajax/request?q=" + str, true);
            xmlhttp.send();
        }
    }
</script>