<h3> Welcome to SEO Framework v.<?php echo $this->getVersion(); ?> </h3>
<div class="content">
    <p> What does our project do?
        We help you solve most of the mistakes that are associated with the promotion of your Internet resource. </p>
    <p>
        For this, we have a sufficiently powerful set of tools that will help you identify problems and get
        recommendations for their solution
    </p>
    <p>
        With the help of our resource you will be able to cover over 90% of the problems associated with common common
        mistakes that prevent the promotion of your Internet resource up to the search engines
    </p>
</div>
<br><br>