<div class="login-form">
    <form>
    <label class="email-label"><b>Email</b></label>
    <i class="fa fa-envelope" aria-hidden="true"></i>
    <input type="text" placeholder="Enter Email" name="email" required>
    <br>
    <label><b>Password</b></label>
    <i class="fa fa-key" aria-hidden="true"></i>
    <input type="password" placeholder="Enter Password" name="password" required>
    <br><br>
    <button type="submit">Login</button>
    <input type="checkbox" checked="checked"> Remember me
    </form>
</div>