<div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li><a href="<?php echo $this->getUrl(); ?>">Home Page</a></li>
        <li><a href="<?php echo $this->getUrl('sitemap'); ?>">Sitemap Tools</a></li>
        <li><a href="<?php echo $this->getUrl('performance'); ?>">Perfomance Tests</a></li>
        <li><a href="<?php echo $this->getUrl('styles'); ?>">Inline Styles</a></li>
        <li><a href="">Security</a></li>
        <li><a href="">SEO Tools </a></li>
    </ul>
</div>
