<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->getUrl(); ?>">Seo Framework <?php echo $this->getVersion(); ?></a> |
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->getUrl('sitemap'); ?>">Sitemap Tools</a></li>
                <li><a href="<?php echo $this->getUrl('performance'); ?>">Perfomance Tests</a></li>
                <li><a href="<?php echo $this->getUrl('styles'); ?>">Inline Styles</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->getUrl('users/register'); ?>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="<?php echo $this->getUrl('users/login'); ?>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>
    </div>
</nav>