<div class="userbar">
    <ul>
        <i class="fa fa-home" aria-hidden="true"></i>
        <li><a href="<?php echo $this->getUrl(); ?>">Home</a></li>
        <i class="fa fa-check-square-o" aria-hidden="true"></i>
        <li><a href="<?php echo $this->getUrl('users/login'); ?>">Login / Register</a></li>
        <i class="fa fa-cog" aria-hidden="true"></i>
        <li><a href="<?php echo $this->getUrl('users/settings'); ?>">Settings</a></li>

    </ul>
</div>
