<div class="userbar">
    <ul>
        <i class="fa fa-home" aria-hidden="true"></i>
        <li><a href="/">Home</a></li>
        <i class="fa fa-check-square-o" aria-hidden="true"></i>
        <li><a href="/users/login">Login / Register</a></li>
        <i class="fa fa-shopping-bag" aria-hidden="true"></i>
        <li><a href="/checkout/cart">Bag</a></li>
        <i class="fa fa-cog" aria-hidden="true"></i>
        <li><a href="/users/settings">Settings</a></li>

    </ul>
</div>
