<h3>Sitemap Tools Page</h3>
<div>
    <p>Welcome to Sitemap SEO Tools</p>
    <p>With this tool you can check the validity of your site map. We will check for you all the links, check the
        correctness of their design, the correctness of the paths, statuses and output the result. If your site map
        reveals problems, we will give you several recommendations how to fix and improve your site map.</p>

</div>