<h2><?php echo 'Last changes: 21.08.2017' ?></h2><br>

<div class="release-notes">
    <h4>Commits on Aug 21, 2017:</h4>
    1. Fixed PHPDoc in Runner::CoreException method<br>
    2. Create new UI element goback.phtml<br>
    3. Refactor error message and validation in Styles feature<br>
    4. Refactor getRequest method for more flexibility<br><br>

    <h4>Commits on Aug 20, 2017:</h4>
    1. Change Perfomance test iteration from 50 to 10<br><br>


    <h4>Commits on Aug 19, 2017:</h4>
    1. Refactor notices. Added type of notification messages <br>
    2. Refactor logic. Add notice logic <br><br>

    <h4>Commits on Aug 18, 2017:</h4>
    1. Change public license url <br>
    2. Fixed: GetUrl, url in userbar template <br>
    3. Refactor template rendering, add ability to pass several template paths into render template method. Transfer rendertemplate into root <br><br>

    <h4>Commits on Aug 15, 2017:</h4>
    1. Initial commit <br>
    2. Change name to Seo Framework <br>
    3. Fixed version output <br>
    4. Added inline styles feature <br><br>
</div>