<?php echo $this->renderTemplate('includes/head'); ?>
<header id="header" class="alt">
    <h2 class="left">Seo Framework <?php echo $this->getVersion(); ?></h2>
    <span>-= Development Preview: <?php echo $this->getVersion(); ?> =-</span>
    <?php $this->renderTemplate('includes/userbar'); ?>
    <div class="clear"></div>
    <?php  $this->renderTemplate('includes/navigation'); ?>
</header>
